version: "3.4"

services:
  # expose docker endpoint using nginx
  docker_proxy_nginx:
    image: "nginx:1.13.8-alpine"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    configs:
      - source: nginx_conf
        target: "/etc/nginx/nginx.conf"
    deploy:
      mode: global
      placement:
        constraints:
         - node.role == manager

  # expose docker endpoint using haproxy
  docker_proxy_haproxy:
    image: "haproxy:1.8.3-alpine"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    configs:
      - source: haproxy_conf
        target: /usr/local/etc/haproxy/haproxy.cfg
    deploy:
      mode: global
      placement:
        constraints:
         - node.role == manager

  traefik:
    image: "traefik:1.5-alpine"
    command:
      - --docker
      - --docker.swarmmode
      - --docker.domain=localtest.me
      # use nginx as docker socket proxy
      - --docker.endpoint=http://docker_endpoint_nginx:4999
      # use haproxy as docker socket proxy
      # - --docker.endpoint=http://docker_endpoint_haproxy:4999
      - --docker.watch
      - --web
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - default
      - proxy
    deploy:
      mode: global

configs:
  nginx_conf:
    file: ./nginx.conf
  haproxy_conf:
    file: ./haproxy.cfg

networks:
  proxy:
    external: true
