version: "3.4"

services:
  docker_socket:
    image: "nginx:1.13.8"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    configs:
      - source: nginx_conf
        target: "/etc/nginx/nginx.conf"
    deploy:
      mode: global
      placement:
        constraints:
         - node.role == manager

  traefik:
    image: "traefik:1.5-alpine"
    command:
      - --docker
      - --docker.swarmmode
      - --docker.domain=localtest.me
      - --docker.endpoint=http://docker_socket:4999
      - --docker.watch
      - --web
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - default
      - proxy
    deploy:
      mode: global

configs:
  nginx_conf:
    file: ./nginx.conf

networks:
  proxy:
    external: true