version: "3.4"

services:
  agent:
    image: python:3.6.4-alpine3.7
    working_dir: /app/agent
    command: sh -c "pip install -r requirements.txt && python main.py"
    configs:
      - source: requirements.txt
        target: /app/agent/requirements.txt
      - source: main.py
        target: /app/agent/main.py
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager

configs:
  requirements.txt:
    file: ./agent/requirements.txt
  main.py:
    file: ./agent/main.py
